Options:
  #The number of rows for a bookshelf (Allows 1-6)
  BookShelfRows: 2

  #Whether to use the item whitelist or not
  UseWhitelist: true

  #Items which is allowed to be placed into a bookshelf
  #See this for item names: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  Whitelist:
    - BOOK
    - WRITABLE_BOOK
    - WRITTEN_BOOK
    - ENCHANTED_BOOK
    - KNOWLEDGE_BOOK

  NoPermissionToReloadMessage: "&cYou do not have permission use this command!"
  NoPermissionToUpdateMessage: "&cYou do not have permission use this command!"

  #Play particles or not when opening a bookshelf
  ParticlesWhenOpened: true
  OpenedParticleColors:
    Frequency: 5
    Primary: "#9933FF"
    Secondary: "#FFFF00"

  #Whether to allow bookshelves to work with hoppers
  #Performace heavy, not recommended
  EnableHopperSupport: false

  #Whether to allow bookshelves to work with droppers
  EnableDropperSupport: false

  #Whether to enable enchantment table boosting
  EnableEnchantmentTableBoosting: true

  #The count of particles when using an enchantment table that is boosted
  #Defaults to 75
  EnchantingParticlesCount: 75
  BoostingParticleColors:
    # This is the frequency of particles on the bookshelves
    Frequency: 5
    Primary: "#CC00CC"
    Secondary: "#3333FF"

  #Max percentage of the enchantment table boosting feature
  #Accepts integer from 1 to 100
  EnchantmentTableBoostingMaxPercentage: 80

  #Disable bookshelves loading in these worlds
  DisabledWorlds: []

  #Enable update notifications for admins
  Updater: true